![logo itq](img/imgitq.jpeg)

## Tercer Módulo-Python, Pandas_2

![logo python](img/imgpython.jpeg)

*Mónica Guano*

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

# Operaciones en pandas

#### Búsqueda

In [3]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  1  2  1
1  0  4  3

In [4]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [5]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False   True  False
1  False  False   True

In [6]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0  False  False  False
1  False   True  False

[[False False False]
 [False  True False]]

numpy.ndarray

In [7]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

3

       A     B      C
0  False  True  False
1  False  True   True

#### Ordenación

In [8]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
4  18  17   6  15
3   0   7   5   0
2  18   9  17  19
1  15  14  18  13
0  19  19   6  18

In [9]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4  18  17   6  15
3   0   7   5   0
2  18   9  17  19
1  15  14  18  13
0  19  19   6  18

    D   A   C   B
4  18  17   6  15
3   0   7   5   0
2  18   9  17  19
1  15  14  18  13
0  19  19   6  18

In [10]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
4  18   6  15  17
3   0   5   0   7
2  18  17  19   9
1  15  18  13  14
0  19   6  18  19

In [11]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
3   0   7   5   0
2  18   9  17  19
1  15  14  18  13
4  18  17   6  15
0  19  19   6  18

In [12]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    B   A   D   C
4  15  17  18   6
3   0   7   0   5
2  19   9  18  17
1  13  14  15  18
0  18  19  19   6

In [13]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
0  19  19   6  18
4  18  17   6  15
1  15  14  18  13
2  18   9  17  19
3   0   7   5   0

#### Ranking
- Construir un ranking de valores

In [14]:
display(frame)

    D   A   C   B
0  19  19   6  18
4  18  17   6  15
1  15  14  18  13
2  18   9  17  19
3   0   7   5   0

In [15]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
0  4.0  4.0  1.0  2.0
4  4.0  3.0  1.0  2.0
1  3.0  2.0  4.0  1.0
2  3.0  1.0  2.0  4.0
3  2.0  4.0  3.0  2.0

In [17]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

18
17
6
6
5

# Operaciones

Operaciones matemáticas entre objetos

In [18]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  49  47  38  85
1  77  68  96  57
2  52  99  61  78
3  45  66  51  91

    0   1   2   3
0   9  29  51  37
1  43  17  36  26
2  97  42  25  64
3  13  43  21   6

In [19]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0   58   76   89  122
1  120   85  132   83
2  149  141   86  142
3   58  109   72   97

In [20]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -40 -18  13 -48
1 -34 -51 -60 -31
2  45 -57 -36 -14
3 -32 -23 -30 -85

In [21]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  49  47  38  85
1  77  68  96  57
2  52  99  61  78
3  45  66  51  91

    0   1   2
0   8  72  18
1  74  31  24
2  68  91  95

       0      1      2   3
0   57.0  119.0   56.0 NaN
1  151.0   99.0  120.0 NaN
2  120.0  190.0  156.0 NaN
3    NaN    NaN    NaN NaN

In [22]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0   57.0  119.0   56.0  85.0
1  151.0   99.0  120.0  57.0
2  120.0  190.0  156.0  78.0
3   45.0   66.0   51.0  91.0

Operadores aritméticos solo válidos en elementos aceptables

In [23]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

pandas se basa en NumPy, np operadores binarios y unarios son aceptables 

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [24]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por columna

   A  B  C  D
0  2  3  5  9
1  8  3  5  6
2  8  7  6  4

0    7
1    5
2    4
dtype: int64

In [25]:
def max_min(x):
    return x.max() - x.min()

print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    6
B    4
C    1
D    5
dtype: int64

In [26]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  1  0  3  6
1  2  0  7  8
2  3  7  1  4

0    6
1    8
2    6
dtype: int64

# Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame

| Operación | Descripción |
|:----------|:------------|
| count | Número de valores no NaN |
| describe | Conjunto de estadísticas sumarias|
| min, max | Valores mínimo y máximo |
| argmin, argmax | Índices posicionales del valor mínimo y máximo |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo |
| sum | Suma de los elementos |
| mean | Media de los elementos |
| median | Mediana de los elementos |
| mad | Desviación absoluta media del valor medio |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos |
| cumsum | Suma acumulada de los elementos |
| diff | Diferencia aritmética de los elementos |

In [27]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30], 
               "puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [28]:
# operadores básicos
print(frame.sum())

display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [29]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [30]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [31]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [32]:
print(frame['edad'].std())

10.996211468804457

In [33]:
frame['edad'].idxmax()

0

In [34]:
frame['puntos'].idxmin()

1

In [35]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())

display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [36]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [37]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## Agregaciones

In [38]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [39]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [40]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [41]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [42]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [43]:
# Filtrado de los datos en el que el conjunto no supera una media determinada 
def media(x):
    return x["edad"].mean() > 30

display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## Correlaciones

pandas incluye métodos para analizar correlaciones
- Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2) --> medida de correlación entre los datos de ambos objetos
- https://blogs.oracle.com/ai-and-datascience/post/introduction-to-correlation

### Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [44]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, sep='\s+', header=None,
            names = ['mpg', 'cilindros', 'desplazamiento','potencia',
            'peso', 'aceleracion', 'año', 'origen', 'nombre'],
            na_values='?', engine='c')

In [45]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
43,13.0,8,400.0,170.0,4746.0,12.0,71,1,ford country squire (sw)
146,28.0,4,90.0,75.0,2125.0,14.5,74,1,dodge colt
6,14.0,8,454.0,220.0,4354.0,9.0,70,1,chevrolet impala
300,23.9,8,260.0,90.0,3420.0,22.2,79,1,oldsmobile cutlass salon brougham
309,41.5,4,98.0,76.0,2144.0,14.7,80,2,vw rabbit

In [46]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [47]:
mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB

### Correlaciones entre valores

In [48]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

np.float64(-0.8317409332443351)

In [49]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

np.float64(-0.4174573199403932)

### Correlaciones entre todos los valores

In [50]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [51]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [52]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [53]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [54]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: object

In [55]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax()  #consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: object

In [56]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: object

In [57]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

## Ejercicios

- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb

In [60]:
import numpy as np
#Consider the following Python dictionary data and Python list labels:

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [61]:
import pandas as pd
import numpy as np

# El diccionario de datos proporcionado
data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

# La lista de etiquetas para el índice
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Creación del DataFrame
df = pd.DataFrame(data, index=labels)

# Visualización del resultado
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [62]:
# Mostrar el resumen de información básica
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

In [63]:
# 1. Mostrar el resumen técnico (estructura, tipos de datos y nulos)
df.info()

# 2. (Opcional) Mostrar el resumen estadístico de las columnas numéricas
print("\nResumen estadístico:")
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

Resumen estadístico:
            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [64]:
# Retornar las primeras 3 filas
primeras_filas = df.head(3)

# Mostrar el resultado
print(primeras_filas)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [65]:
# Seleccionar solo las columnas 'animal' y 'age'
seleccion = df[['animal', 'age']]

# Mostrar el resultado
print(seleccion)

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [66]:
# Opción 1: Usando las etiquetas de las filas (si conoces que 3, 4, 8 corresponden a d, e, i)
seleccion = df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

# Opción 2: Usando .iloc (basado puramente en posiciones enteras)
# 'animal' es la columna 0 y 'age' es la columna 1
seleccion_posicional = df.iloc[[3, 4, 8], [0, 1]]

print(seleccion)

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [67]:
# Seleccionar filas donde el número de visitas sea mayor a 3
resultado = df[df['visits'] > 3]

# Mostrar el resultado
print(resultado)

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [68]:
# Seleccionar las filas donde la edad es NaN (valores perdidos)
filas_con_nan = df[df['age'].isnull()]

# Mostrar el resultado
print(filas_con_nan)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [69]:
# Seleccionar las filas donde la edad es NaN
filas_sin_edad = df[df['age'].isnull()]

# Mostrar el resultado
print(filas_sin_edad)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [70]:
# Filtrar filas: animal es 'cat' Y edad es menor que 3
filtro_gatos_jovenes = df[(df['animal'] == 'cat') & (df['age'] < 3)]

# Mostrar el resultado
print(filtro_gatos_jovenes)

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


### [Link Github: Pandas2](https://github.com/moniloag-png/Introduccionpythonnocturno/blob/main/PAO25_25_08_Python_%2BPandas%20.ipynb)